---

- name: TEST CONNECTIVITY TO DEVICES
  hosts: all
  gather_facts: false
  connection: network_cli
  become_method: enable

  tasks:
    - name: PING Devices
      ansible.builtin.ping:
        data: "PING"